default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: miru_web_development

test:
  <<: *default
  database: miru_web_test

# production:
#   <<: *default
#   url: <%= ENV['DATABASE_URL'] %>
